FROM maven:3.9.8-eclipse-temurin-21

# Install Node.js, Git und Tools
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get update && apt-get install -y \
    curl \
    git \
    nodejs \
    vim \
    wget \
    && git config --global init.defaultBranch main \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY pom.xml .
RUN mvn dependency:go-offline || true

CMD ["sleep", "infinity"]