FROM maven:3.9.8-eclipse-temurin-21

RUN apt-get update && apt-get install -y \
    git \
    curl \
    wget \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN git config --global init.defaultBranch main

WORKDIR /workspace

COPY pom.xml .
RUN mvn dependency:go-offline || true

CMD ["sleep", "infinity"]