FROM maven:3.9.8-eclipse-temurin-21

# Install Node.js, Git und Tools
RUN apt-get update && apt-get install -y \
    curl \
    git \
    vim \
    wget \
    && apt-get install -y git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /workspace

COPY pom.xml .
RUN mvn dependency:go-offline || true

CMD ["sleep", "infinity"]